version: "3.9"

services:
  db:
    build:
      context: db/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - veerush-network

volumes:
  db-data:

networks:
  veerush-network:
    external: true
